name = "OceanDistributions"
uuid = "aa3b323a-0e68-4b14-b952-9911d94e084a"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.5, 0.6, 0.7, 0.8, 0.9"
DataFrames = "1"
julia = "1"
