name = "OceanDistributions"
uuid = "aa3b323a-0e68-4b14-b952-9911d94e084a"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
CSV = "0.5, 0.6, 0.7, 0.8, 0.9"
julia = "1"
